# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='Session',
            new_name='session',
        ),
    ]
